//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;

use super::sea_orm_active_enums::RankTierEnum;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(schema_name = "dodgetracker", table_name = "apex_tier_players")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub summoner_id: String,
    pub summoner_name: Option<String>,
    #[sea_orm(primary_key, auto_increment = false)]
    pub region: String,
    pub current_lp: i64,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    pub wins: i64,
    pub losses: i64,
    pub rank_tier: RankTierEnum,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
