//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;

use super::sea_orm_active_enums::RankTierEnum;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(schema_name = "dodgetracker", table_name = "dodges")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub dodge_id: i64,
    pub summoner_id: String,
    pub region: String,
    pub lp_before: i64,
    pub lp_after: i64,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    pub at_wins: i64,
    pub at_losses: i64,
    pub rank_tier: RankTierEnum,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
