//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;

use super::sea_orm_active_enums::RankTier;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "dodges")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub dodge_id: i32,
    pub summoner_id: String,
    pub region: String,
    pub lp_before: i32,
    pub lp_after: i32,
    pub rank_tier: RankTier,
    pub created_at: DateTimeUtc,
    pub updated_at: DateTimeUtc,
    pub at_wins: i32,
    pub at_losses: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
