//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "promotions")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub promotion_id: i32,
    pub summoner_id: String,
    pub region: String,
    pub created_at: DateTimeUtc,
    pub updated_at: DateTimeUtc,
    pub at_wins: i32,
    pub at_losses: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
