name: ESLint Check

on: [push]

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20" # Adjust this to the Node.js version your project uses

      - name: Install Dependencies
        run: npm install

      - name: Run ESLint Check
        run: npx eslint '**/*.{js,jsx,ts,tsx}' --quiet --ignore-path .gitignore
