name: Prettier Check

on: [push]

jobs:
    prettier:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Set up Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: "20"

            - name: Install Dependencies
              run: npm install

            - name: Check Formatting
              run: npx prettier --check '**/*.{js,jsx,ts,tsx,css,md,json,html}'
